name: Publish
on:
  push:
    branches: master
  schedule: 
    - cron: '0 20 * * *'
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'boozallen/sdp-docs'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
      with: 
        persist-credentials: false
    - name: Build Docs 
      run: make docs
    - uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: .
      env: 
        ACTIONS_STEP_DEBUG: true
